class AgentFrameworkError(Exception): ...


class ConfigurationError(AgentFrameworkError): ...


class ToolNotFoundError(AgentFrameworkError): ...


class ToolExecutionError(AgentFrameworkError): ...


class GuardrailViolationError(AgentFrameworkError): ...


class TokenBudgetExceededError(AgentFrameworkError): ...


class RateLimitExceededError(AgentFrameworkError): ...


class AgentMemoryError(AgentFrameworkError): ...


class RunNotFoundError(AgentFrameworkError): ...


class RouterError(AgentFrameworkError): ...
